# Generated by Django 5.2.7 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('external', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado al Cliente'), ('approved', 'Aprobado (Parcial o Total)'), ('rejected', 'Rechazado')], default='draft', max_length=20)),
                ('folio', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Folio')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clients.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo estimado')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobado por cliente')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.evaluation')),
                ('external_service_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='external.externalservice')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_items', to='inventory.product')),
            ],
        ),
    ]
