# Generated by Django 5.2.7 on 2025-10-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalService', '0002_externalservice_category_alter_externalservice_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservice',
            name='available_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos', null=True),
        ),
    ]
