# Generated by Django 5.2.7 on 2025-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalService', '0003_externalservice_available_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='external_services/'),
        ),
    ]
