# Generated by Django 5.2.7 on 2025-12-05 21:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre Producto')),
                ('sku', models.CharField(max_length=64, verbose_name='Código SKU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='Ubicación')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='Cantidad Entrada')),
                ('current_quantity', models.PositiveIntegerField(verbose_name='Stock Actual')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Compra')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['expiration_date', 'entry_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('owner', 'sku'), name='unique_product_sku_per_owner'),
        ),
    ]
