# Generated by Django 5.2.7 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Folio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Reparación'), ('waiting_parts', 'Esperando Repuestos'), ('finished', 'Terminado'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas para mecánico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='evaluations.evaluation')),
                ('last_status_change_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
