# Generated by Django 5.2.7 on 2025-10-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('awaiting_approval', 'Esperando Aprobación'), ('in_progress', 'En Taller'), ('awaiting_parts', 'Esperando Repuestos'), ('done', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('client_name', models.CharField(max_length=120, verbose_name='Nombre Cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=100, verbose_name='Email Cliente')),
                ('vehicle_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente')),
                ('vehicle_make', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('vehicle_vin', models.CharField(blank=True, max_length=17, verbose_name='VIN (Chasis)')),
                ('service_title', models.CharField(max_length=160, verbose_name='Título del Servicio')),
                ('service_description', models.TextField(blank=True, verbose_name='Notas / Descripción del problema')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Agendada')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Estimado')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Final')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
