# Generated by Django 5.2.7 on 2025-11-03 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalService', '0004_externalservice_image'),
        ('orders', '0002_alter_order_final_cost_orderitem_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_at_booking', models.CharField(max_length=255)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings_through', to='orders.order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='externalService.externalservice')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('order', 'service', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_bookings',
            field=models.ManyToManyField(related_name='orders', through='orders.ExternalServiceBooking', to='externalService.externalservice'),
        ),
    ]
